repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # You can run pre-commit autoupdate to get the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.8.0  # You can run pre-commit autoupdate to get the latest version
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2  # You can run pre-commit autoupdate to get the latest version
    hooks:
    -   id: isort
        args:
        - --profile=black  # This ensures isort uses the black profile for sorting imports

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # You can run pre-commit autoupdate to get the latest version
    hooks:
    -   id: flake8

# -   repo: https://github.com/charliermarsh/ruff-pre-commit
#     rev: v0.6.2  # You can run pre-commit autoupdate to get the latest version
#     hooks:
#     -   id: ruff
